### ISSUE TITLE
link

### ISSUE THREAD

**Issue by monavariyas** [panchalyogesh774/PostgreSQL#14]
For link  'Setup the repository for pgadmin', there is no content showing on clicking the link

**Comment by panchalyogesh774** [comment]
This link is only meant for use in the terminal. If you paste it into the search bar, the PgAdmin file will be downloaded for desktop use.

**Comment by monavariyas** [comment]
- First of all make the heading bold.
- You should write this in your document.

**Comment by monavariyas** [comment]
Hi Yogesh,

- Setup the repository for pgadmin:   you mean to say for setup the repository ,we need to install public key?  if yes please make the Setup the repository for pgadmin bold as it is the main heading.
![ImageJ](https://github.com/panchalyogesh774/PostgreSQL/assets/146812602/f2c96552-0ab2-4064-aeea-684f00e79ebe)
