### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by monavariyas** [panchalyogesh774/PostgreSQL#19]
Images are showing at my end.

**Comment by panchalyogesh774** [comment]
Ma'am ,I didn't understand ,what do you want to say.

**Comment by monavariyas** [comment]
![Image1](https://github.com/panchalyogesh774/PostgreSQL/assets/146812602/b368bb54-47eb-4fdf-8048-50df114ca0b3)

Please refer to the image 

Images are not showing.
